scene_objects:
# - {type: "blank_piece_location",  frame: "table", position: [0.298, 0.500, 0.139], quaternion: [0,0,0,1]}
# - {type: "L_plate",  frame: "table", position: [0.306, 0.506, 0.146], quaternion: [0,0,0,1]}
- {type: "cube",  frame: "table", position: [0.299, 0.498, 0.168], quaternion: [0,0,0,1]}
