scene_objects:
# - {type: "squadra_piccola",  frame: "table", position: [ 0.2, 1.005, 0.28], quaternion: [0,0,0,1]}
# - {type: "squadra_piccola",  frame: "table", position: [ 0.2, 1.078, 0.28], quaternion: [0,0,0,1]}
- {type: "squadra_piccola",  frame: "table", position: [ 0.2, 1.136, 0.28], quaternion: [0,0,0,1]}
# - {type: "cube",             frame: "table", position: [ 0.2, 1.208, 0.28], quaternion: [0,0,0,1]}
# - {type: "cube",             frame: "table", position: [ 0.2, 1.268, 0.28], quaternion: [0,0,0,1]}
- {type: "pin",              frame: "table", position: [ 0.2, 0.529, 0.28], quaternion: [ 0, 0, -0.7071068, 0.7071068 ]}
# - {type: "pin",              frame: "table", position: [ 0.2, 0.673, 0.28], quaternion: [ 0, 0, -0.7071068, 0.7071068 ]}
# - {type: "squadra_grande",   frame: "table", position: [ 0.2, 0.803, 0.28], quaternion: [ 0, 0, -0.7071068, 0.7071068 ]}
# - {type: "squadra_grande",   frame: "table", position: [ 0.2, 0.930, 0.28], quaternion: [ 0, 0, -0.7071068, 0.7071068 ]}

# manipulation_objects_geometry:
#   squadra_piccola:
#     color: [0.2,0.2,0.2, 1.]
#     box:  [0.019,0.03,0.012]
#     offset_quaternion: [ 0, 0, 0, 1 ]
#     offset: [0, 0, 0]
#
#   pin:
#     color: [0.2,0.2,0.2, 0.4]
#     box:  [0.02,0.02,0.06]
#     offset_quaternion: [ 0, 0, 0, 1 ]
#     offset: [0, 0, 0]
#
#   squadra_grande:
#     color: [0.2,0.2,0.2, 1.]
#     box:  [0.03,0.01,0.03]
#     offset_quaternion: [ 0, 0, 0, 1 ]
#     offset: [0, 0, 0]
#
#   cube:
#     color: [0.2,0.2,0.2, 0.4]
#     box:  [0.03,0.03,0.03]
#     offset_quaternion: [ 0, 0, 0, 1 ]
#     offset: [0, 0, 0]
